version: '3.8'

services:
  backend:
    build: ./backend
    container_name: file-manager-backend
    ports:
      - "${BACKEND_PORT:-3001}:${BACKEND_PORT:-3001}"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BACKEND_DOMAIN=${BACKEND_DOMAIN:-localhost}
      - BACKEND_PORT=${BACKEND_PORT:-3001}
      - BACKEND_PROTOCOL=${BACKEND_PROTOCOL:-http}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN:-localhost}
      - FRONTEND_PORT=${FRONTEND_PORT:-3002}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL:-http}
      - PRODUCTION_DOMAIN=${PRODUCTION_DOMAIN}
      - PRODUCTION_PROTOCOL=${PRODUCTION_PROTOCOL:-https}

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_BACKEND_DOMAIN=${VITE_BACKEND_DOMAIN:-localhost}
        - VITE_BACKEND_PORT=${VITE_BACKEND_PORT:-3001}
        - VITE_BACKEND_PROTOCOL=${VITE_BACKEND_PROTOCOL:-http}
        - VITE_PRODUCTION_DOMAIN=${VITE_PRODUCTION_DOMAIN}
        - VITE_PRODUCTION_PROTOCOL=${VITE_PRODUCTION_PROTOCOL:-https}
    container_name: file-manager-frontend
    ports:
      - "${FRONTEND_PORT:-3002}:80"
    depends_on:
      - backend

volumes:
  data:
  uploads: